apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
    - hosts:
        - dnd4.ru
        - express.dnd4.ru
      secretName: tls-secret
  rules:
    - host: dnd4.ru
      http:
        paths:
          - path: /
            backend:
              serviceName: webui-service
              servicePort: 80
    - host: express.dnd4.ru
      http:
        paths:
          - path: /
            backend:
              serviceName: mongo-express-service
              servicePort: 8081
